<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.wangbin</groupId>
    <artifactId>data-collection-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>collector-web</artifactId>
  <name>collector-web</name>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-protocol-spi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-runtime</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-telemetry</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-cloud</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-monitor</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.wangbin</groupId>
      <artifactId>collector-application</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
