package com.wangbin.collector.storage.buffer;

import java.util.Map;

/**
 * 历史批量写入的内部观测快照。
 */
public record HistoryBatchMetrics(long acceptedRows,
                                  long flushedBatches,
                                  long flushedRows,
                                  long batchWriteSuccess,
                                  long batchWriteFailure,
                                  long fallbackRows,
                                  int currentBufferedRows,
                                  int bufferedRowsPeak,
                                  double averageBatchSize,
                                  int batchSizeP50,
                                  int batchSizeP95,
                                  int batchSizeMax,
                                  double flushLatencyP50Ms,
                                  double flushLatencyP95Ms,
                                  double flushLatencyP99Ms,
                                  long oldestBufferedAgeMs,
                                  long shutdownFlushedRows,
                                  long fallbackRedisRows,
                                  long fallbackLocalRows,
                                  long fallbackDroppedRows,
                                  long fallbackDisabledRows,
                                  long shutdownDeferredRows,
                                  long shutdownNonDurableRows,
                                  long shutdownDroppedRows,
                                  long shutdownDisabledRows,
                                  long flushExecutorSubmittedBatches,
                                  long flushExecutorCompletedBatches,
                                  long flushExecutorRejectedBatches,
                                  int flushExecutorQueueCurrent,
                                  int flushExecutorQueuePeak,
                                  int flushExecutorActiveCurrent,
                                  int flushExecutorActivePeak,
                                  long shutdownQueuedBatches,
                                  int bucketCount,
                                  int admissionInFlight,
                                  int inFlightFlushes,
                                  long sizeFlushBatches,
                                  long timerFlushBatches,
                                  long sizeFlushRows,
                                  long timerFlushRows,
                                  double sizeAverageBatchSize,
                                  int sizeBatchSizeP50,
                                  int sizeBatchSizeP95,
                                  int sizeBatchSizeMax,
                                  double timerAverageBatchSize,
                                  int timerBatchSizeP50,
                                  int timerBatchSizeP95,
                                  int timerBatchSizeMax,
                                  double tdengineBatchCallsPerSecond,
                                  double flushExecutorServiceRatePerSecond,
                                  double flushExecutorQueueUtilization,
                                  long tdengineWriteRequests,
                                  long tdengineWriteRows,
                                  double tdengineWriteRequestsPerSecond,
                                  double tdengineRowsPerRequest,
                                  int tdengineRowsPerRequestP95,
                                  int tdengineRowsPerRequestMax,
                                  double tdengineTablesPerRequest,
                                  int tdengineTablesPerRequestP95,
                                  int tdengineTablesPerRequestMax,
                                  long multiTableWriteRequests,
                                  long multiTableWriteRows,
                                  long multiTableAggregatedBatches,
                                  Map<String, Integer> activeWritesBySubTable,
                                  int maxConcurrentWritesSameSubTable,
                                  long sameSubTableConcurrentWriteCount,
                                  double dbQueueWaitP50Ms,
                                  double dbQueueWaitP95Ms,
                                  double dbQueueWaitP99Ms,
                                  double dbExecuteLatencyP50Ms,
                                  double dbExecuteLatencyP95Ms,
                                  double dbExecuteLatencyP99Ms,
                                  Map<String, Double> subTableWriteLatencyP95Ms) {
}
